BEGIN TRANSACTION;

INSERT INTO standings (
    tournament_id,
    team_id,
    "group",
    position,
    points,
    wins,
    draws,
    losses,
    goals_for,
    goals_against
)
VALUES
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 16), 'A', 1, 9, 3, 0, 0, 6, 0),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1531), 'A', 2, 4, 1, 1, 1, 2, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 17), 'A', 3, 3, 1, 0, 2, 2, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 770), 'A', 4, 1, 0, 1, 2, 2, 6),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 15), 'B', 1, 7, 2, 1, 0, 7, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5529), 'B', 2, 4, 1, 1, 1, 8, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1113), 'B', 3, 4, 1, 1, 1, 5, 6),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1569), 'B', 4, 1, 0, 1, 2, 2, 10),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 6), 'C', 1, 7, 2, 1, 0, 7, 1),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 31), 'C', 2, 7, 2, 1, 0, 6, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1108), 'C', 3, 3, 1, 0, 2, 1, 4),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2386), 'C', 4, 0, 0, 0, 3, 2, 8),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2384), 'D', 1, 6, 2, 0, 1, 8, 4),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 20), 'D', 2, 4, 1, 1, 1, 2, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2380), 'D', 3, 4, 1, 1, 1, 2, 4),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 777), 'D', 4, 3, 1, 0, 2, 3, 5),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 25), 'E', 1, 6, 2, 0, 1, 10, 4),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1501), 'E', 2, 6, 2, 0, 1, 4, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2382), 'E', 3, 4, 1, 1, 1, 2, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5530), 'E', 4, 1, 0, 1, 2, 1, 9),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1118), 'F', 1, 7, 2, 1, 0, 10, 4),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 12), 'F', 2, 5, 1, 2, 0, 7, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5), 'F', 3, 4, 1, 1, 1, 7, 7),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 28), 'F', 4, 0, 0, 0, 3, 2, 12),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1), 'G', 1, 5, 1, 2, 0, 6, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 32), 'G', 2, 5, 1, 2, 0, 5, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 22), 'G', 3, 3, 0, 3, 0, 3, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 4673), 'G', 4, 1, 0, 1, 2, 4, 10),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 9), 'H', 1, 7, 2, 1, 0, 5, 0),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1533), 'H', 2, 3, 0, 3, 0, 2, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 7), 'H', 3, 2, 0, 2, 1, 3, 4),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 23), 'H', 4, 2, 0, 2, 1, 1, 5),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), 'I', 1, 9, 3, 0, 0, 10, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1090), 'I', 2, 6, 2, 0, 1, 8, 7),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 13), 'I', 3, 3, 1, 0, 2, 8, 6),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1567), 'I', 4, 0, 0, 0, 3, 1, 12),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 26), 'J', 1, 9, 3, 0, 0, 8, 1),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 775), 'J', 2, 4, 1, 1, 1, 6, 6),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1532), 'J', 3, 4, 1, 1, 1, 5, 7),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1548), 'J', 4, 0, 0, 0, 3, 3, 8),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 8), 'K', 1, 7, 2, 1, 0, 4, 1),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 27), 'K', 2, 5, 1, 2, 0, 6, 1),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1508), 'K', 3, 4, 1, 1, 1, 4, 3),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1568), 'K', 4, 0, 0, 0, 3, 2, 11),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), 'L', 1, 7, 2, 1, 0, 6, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 3), 'L', 2, 6, 2, 0, 1, 5, 5),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1504), 'L', 3, 4, 1, 1, 1, 2, 2),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 11), 'L', 4, 0, 0, 0, 3, 0, 4)
ON CONFLICT (tournament_id, team_id)
DO UPDATE SET
    "group" = EXCLUDED."group",
    position = EXCLUDED.position,
    points = EXCLUDED.points,
    wins = EXCLUDED.wins,
    draws = EXCLUDED.draws,
    losses = EXCLUDED.losses,
    goals_for = EXCLUDED.goals_for,
    goals_against = EXCLUDED.goals_against;

COMMIT TRANSACTION;
