BEGIN TRANSACTION;

INSERT INTO player_leaderboards (
    tournament_id,
    team_id,
    player_id,
    category,
    rank,
    value,
    appearances,
    minutes_played,
    rating
)
VALUES
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 278), 'goals', 1, 10, 8, 698, 8.21),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 154), 'goals', 2, 8, 8, 740, 8.85),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 129718), 'goals', 3, 7, 8, 629, 7.80),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1090), (SELECT id FROM players WHERE external_api_id = 1100), 'goals', 4, 7, 5, 465, 7.94),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 153), 'goals', 5, 6, 8, 597, 7.89),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 184), 'goals', 6, 6, 7, 654, 7.19),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 47323), 'goals', 7, 5, 8, 605, 7.19),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 16), (SELECT id FROM players WHERE external_api_id = 35532), 'goals', 8, 4, 5, 414, 7.76),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 762), 'goals', 9, 4, 5, 441, 8.04),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 2218), 'goals', 10, 4, 4, 366, 7.65),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 26475), 'goals', 11, 3, 4, 149, 7.30),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 406244), 'goals', 12, 3, 4, 200, 7.70),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 161904), 'goals', 13, 3, 8, 384, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1), (SELECT id FROM players WHERE external_api_id = 907), 'goals', 14, 3, 6, 236, 6.78),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1), (SELECT id FROM players WHERE external_api_id = 147859), 'goals', 15, 3, 5, 353, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 247), 'goals', 16, 3, 4, 371, 7.43),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 1165), 'goals', 17, 3, 5, 293, 7.38),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 161897), 'goals', 18, 3, 5, 385, 7.04),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 8489), 'goals', 19, 3, 5, 428, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 38750), 'goals', 20, 3, 4, 232, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 19617), 'assists', 1, 7, 8, 650, 7.34),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 278), 'assists', 2, 4, 8, 698, 8.21),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 154), 'assists', 3, 4, 8, 740, 8.85),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 744), 'assists', 4, 4, 6, 462, 6.85),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 10135), 'assists', 5, 4, 5, 419, 7.16),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1090), (SELECT id FROM players WHERE external_api_id = 37127), 'assists', 6, 4, 5, 471, 7.00),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 1460), 'assists', 7, 3, 7, 357, 7.33),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1090), (SELECT id FROM players WHERE external_api_id = 301528), 'assists', 8, 3, 6, 251, 7.12),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 138787), 'assists', 9, 3, 6, 412, 6.85),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5), (SELECT id FROM players WHERE external_api_id = 2864), 'assists', 10, 3, 4, 358, 7.00),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 16), (SELECT id FROM players WHERE external_api_id = 2879), 'assists', 11, 3, 5, 443, 7.32),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 203224), 'assists', 12, 3, 4, 363, 7.70),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 153), 'assists', 13, 2, 8, 597, 7.89),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 26475), 'assists', 14, 2, 4, 149, 7.30),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 406244), 'assists', 15, 2, 4, 200, 7.70),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1), (SELECT id FROM players WHERE external_api_id = 1946), 'assists', 16, 2, 6, 510, 7.53),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 37724), 'assists', 17, 2, 4, 253, 7.58),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 421), 'assists', 18, 2, 6, 506, 6.85),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 2937), 'assists', 19, 2, 7, 571, 7.36),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1), (SELECT id FROM players WHERE external_api_id = 78), 'assists', 20, 2, 6, 324, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 18814), 'yellow_cards', 1, 3, 5, 477, 6.94),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 271), 'yellow_cards', 2, 2, 7, 473, 7.17),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 2937), 'yellow_cards', 3, 2, 7, 571, 7.36),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 30776), 'yellow_cards', 4, 2, 7, 611, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 2467), 'yellow_cards', 5, 2, 7, 626, 7.29),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 1464), 'yellow_cards', 6, 2, 6, 600, 7.60),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 327738), 'yellow_cards', 7, 2, 5, 379, 6.64),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 747), 'yellow_cards', 8, 2, 5, 379, 7.42),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 618), 'yellow_cards', 9, 2, 5, 405, 6.64),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 190575), 'yellow_cards', 10, 2, 5, 434, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 336671), 'yellow_cards', 11, 2, 5, 450, 7.12),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 16804), 'yellow_cards', 12, 2, 5, 466, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 636), 'yellow_cards', 13, 2, 4, 103, 6.43),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 2001), 'yellow_cards', 14, 2, 4, 189, 6.78),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2382), (SELECT id FROM players WHERE external_api_id = 16360), 'yellow_cards', 15, 2, 4, 254, 6.75),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1508), (SELECT id FROM players WHERE external_api_id = 365331), 'yellow_cards', 16, 2, 4, 258, 6.88),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 1504), (SELECT id FROM players WHERE external_api_id = 475575), 'yellow_cards', 17, 2, 4, 272, 6.73),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 2380), (SELECT id FROM players WHERE external_api_id = 278370), 'yellow_cards', 18, 2, 4, 307, 6.35),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 775), (SELECT id FROM players WHERE external_api_id = 711), 'yellow_cards', 19, 2, 4, 333, 5.70),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2026'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 16841), 'yellow_cards', 20, 2, 4, 359, 6.93)
ON CONFLICT (tournament_id, category, player_id)
DO UPDATE SET
    team_id = EXCLUDED.team_id,
    rank = EXCLUDED.rank,
    value = EXCLUDED.value,
    appearances = EXCLUDED.appearances,
    minutes_played = EXCLUDED.minutes_played,
    rating = EXCLUDED.rating;

COMMIT TRANSACTION;
