sonar.projectKey=daniyal-h_soccer-tournament-dashboard
sonar.organization=daniyal-h

sonar.sources=frontend/src,backend/app
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/tests/**/*.py

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=\
**/node_modules/**,\
**/__pycache__/**,\
backend/alembic/versions/**,\
database/scripts/seeds/**,\
database/scripts/generators/**,\
**/.gitkeep,\
frontend/src/components/ui/**