BEGIN TRANSACTION;

INSERT INTO player_leaderboards (
    tournament_id,
    team_id,
    player_id,
    category,
    rank,
    value,
    appearances,
    minutes_played,
    rating
)
VALUES
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 217), 'goals', 1, 5, 6, 222, 7.07),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2379), (SELECT id FROM players WHERE external_api_id = 2461), 'goals', 2, 3, 4, 337, 7.60),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 24810), 'goals', 3, 2, 6, 418, 7.05),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 51776), 'goals', 4, 2, 6, 448, 7.27),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 13736), 'goals', 5, 2, 5, 389, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 863), 'goals', 6, 2, 6, 176, 6.77),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 6009), 'goals', 7, 2, 6, 348, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 8489), 'goals', 8, 2, 6, 446, 6.93),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 51617), 'goals', 9, 2, 6, 475, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 2490), 'goals', 10, 2, 5, 425, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2379), (SELECT id FROM players WHERE external_api_id = 11765), 'goals', 11, 2, 4, 290, 7.12),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 11), (SELECT id FROM players WHERE external_api_id = 2983), 'goals', 12, 2, 4, 298, 7.02),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2384), (SELECT id FROM players WHERE external_api_id = 138835), 'goals', 13, 2, 3, 178, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 762), 'goals', 14, 2, 3, 251, 7.27),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 2489), 'goals', 15, 2, 6, 512, 6.92),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 50826), 'goals', 16, 1, 6, 348, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 51572), 'goals', 17, 1, 6, 356, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 70078), 'goals', 18, 1, 6, 450, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 154), 'goals', 19, 1, 5, 426, 7.56),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2380), (SELECT id FROM players WHERE external_api_id = 196298), 'goals', 20, 1, 3, 133, 7.07),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 517), 'assists', 1, 6, 6, 467, 8.05),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 6716), 'assists', 2, 2, 6, 445, 7.22),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 5996), 'assists', 3, 2, 5, 353, 7.16),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 5995), 'assists', 4, 2, 5, 354, 7.36),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2379), (SELECT id FROM players WHERE external_api_id = 199044), 'assists', 5, 2, 4, 261, 8.30),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2379), (SELECT id FROM players WHERE external_api_id = 2461), 'assists', 6, 1, 4, 337, 7.60),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 24810), 'assists', 7, 1, 6, 418, 7.05),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 51776), 'assists', 8, 1, 6, 448, 7.27),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 13736), 'assists', 9, 1, 5, 389, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 50826), 'assists', 10, 1, 6, 348, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 51572), 'assists', 11, 1, 6, 356, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 70078), 'assists', 12, 1, 6, 450, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 154), 'assists', 13, 1, 5, 426, 7.56),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2380), (SELECT id FROM players WHERE external_api_id = 196298), 'assists', 14, 1, 3, 133, 7.07),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2384), (SELECT id FROM players WHERE external_api_id = 17), 'assists', 15, 1, 3, 270, 7.33),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 1646), 'assists', 16, 1, 4, 295, 7.42),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 1578), 'assists', 17, 1, 6, 149, 6.70),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 2612), 'assists', 18, 1, 6, 163, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 101814), 'assists', 19, 1, 6, 258, 7.45),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 51535), 'assists', 20, 1, 6, 263, 6.84),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 328046), 'yellow_cards', 1, 3, 6, 319, 7.00),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2383), (SELECT id FROM players WHERE external_api_id = 11421), 'yellow_cards', 2, 2, 3, 207, 6.17),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 13736), 'yellow_cards', 3, 2, 5, 389, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 351587), 'yellow_cards', 4, 2, 6, 133, 6.08),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 1578), 'yellow_cards', 5, 2, 6, 149, 6.70),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 24810), 'yellow_cards', 6, 2, 6, 418, 7.05),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 5529), (SELECT id FROM players WHERE external_api_id = 51295), 'yellow_cards', 7, 2, 6, 428, 6.87),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 7), (SELECT id FROM players WHERE external_api_id = 5995), 'yellow_cards', 8, 2, 5, 354, 7.36),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 8), (SELECT id FROM players WHERE external_api_id = 2490), 'yellow_cards', 9, 2, 5, 425, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 1646), 'yellow_cards', 10, 2, 4, 295, 7.42),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 195103), 'yellow_cards', 11, 2, 4, 327, 6.62),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2382), (SELECT id FROM players WHERE external_api_id = 116117), 'yellow_cards', 12, 2, 4, 360, 7.35),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 11), (SELECT id FROM players WHERE external_api_id = 328148), 'yellow_cards', 13, 2, 4, 360, 6.40),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2379), (SELECT id FROM players WHERE external_api_id = 2459), 'yellow_cards', 14, 2, 3, 124, 6.47),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2385), (SELECT id FROM players WHERE external_api_id = 19373), 'yellow_cards', 15, 2, 3, 156, 6.77),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 11), (SELECT id FROM players WHERE external_api_id = 57904), 'yellow_cards', 16, 2, 3, 205, 6.73),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 762), 'yellow_cards', 17, 2, 3, 251, 7.27),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 30), (SELECT id FROM players WHERE external_api_id = 48379), 'yellow_cards', 18, 2, 3, 259, 6.57),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2384), (SELECT id FROM players WHERE external_api_id = 126949), 'yellow_cards', 19, 2, 3, 270, 7.17),
((SELECT id FROM tournaments WHERE external_api_id = 9 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 29), (SELECT id FROM players WHERE external_api_id = 13898), 'yellow_cards', 20, 2, 2, 110, 6.25)
ON CONFLICT (tournament_id, category, player_id)
DO UPDATE SET
    team_id = EXCLUDED.team_id,
    rank = EXCLUDED.rank,
    value = EXCLUDED.value,
    appearances = EXCLUDED.appearances,
    minutes_played = EXCLUDED.minutes_played,
    rating = EXCLUDED.rating;

COMMIT TRANSACTION;
