BEGIN TRANSACTION;

INSERT INTO player_leaderboards (
    tournament_id,
    team_id,
    player_id,
    category,
    rank,
    value,
    appearances,
    minutes_played,
    rating
)
VALUES
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 1323), 'goals', 1, 3, 6, 431, 7.75),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 247), 'goals', 2, 3, 6, 525, 7.73),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 181812), 'goals', 3, 3, 5, 423, 7.42),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 773), (SELECT id FROM players WHERE external_api_id = 15328), 'goals', 4, 3, 4, 335, 7.13),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 184), 'goals', 5, 3, 7, 606, 7.04),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1104), (SELECT id FROM players WHERE external_api_id = 180496), 'goals', 6, 3, 4, 347, 6.95),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 328), 'goals', 7, 2, 6, 542, 7.97),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 129718), 'goals', 8, 2, 7, 671, 7.44),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 183799), 'goals', 9, 2, 6, 495, 7.23),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 25391), 'goals', 10, 2, 5, 161, 7.10),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 203224), 'goals', 11, 2, 5, 281, 7.38),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 421), 'goals', 12, 2, 5, 297, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 249), 'goals', 13, 2, 4, 190, 7.30),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 777), (SELECT id FROM players WHERE external_api_id = 30521), 'goals', 14, 2, 4, 206, 7.70),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 774), (SELECT id FROM players WHERE external_api_id = 2118), 'goals', 15, 2, 4, 356, 7.03),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 978), 'goals', 16, 2, 5, 391, 6.88),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 386828), 'goals', 17, 1, 7, 506, 7.26),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 162016), 'goals', 18, 1, 6, 456, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 777), (SELECT id FROM players WHERE external_api_id = 291964), 'goals', 19, 1, 5, 342, 7.34),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 2807), 'goals', 20, 1, 5, 459, 7.06),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 386828), 'assists', 1, 4, 7, 506, 7.26),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 162016), 'assists', 2, 3, 6, 456, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 1323), 'assists', 3, 2, 6, 431, 7.75),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 328), 'assists', 4, 2, 6, 542, 7.97),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 777), (SELECT id FROM players WHERE external_api_id = 291964), 'assists', 5, 2, 5, 342, 7.34),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 2807), 'assists', 6, 2, 5, 459, 7.06),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 951), 'assists', 7, 2, 5, 477, 7.34),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 502), 'assists', 8, 2, 5, 480, 7.82),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 777), (SELECT id FROM players WHERE external_api_id = 37155), 'assists', 9, 2, 4, 229, 6.65),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 774), (SELECT id FROM players WHERE external_api_id = 43036), 'assists', 10, 2, 4, 266, 6.83),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 247), 'assists', 11, 1, 6, 525, 7.73),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1104), (SELECT id FROM players WHERE external_api_id = 180496), 'assists', 12, 1, 4, 347, 6.95),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 129718), 'assists', 13, 1, 7, 671, 7.44),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 183799), 'assists', 14, 1, 6, 495, 7.23),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 978), 'assists', 15, 1, 5, 391, 6.88),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 47323), 'assists', 16, 1, 7, 196, 6.74),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 59), 'assists', 17, 1, 7, 454, 6.84),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 25416), 'assists', 18, 1, 6, 139, 6.73),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 667), 'assists', 19, 1, 6, 461, 7.00),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 152982), 'assists', 20, 1, 5, 145, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 44), 'yellow_cards', 1, 3, 6, 521, 7.25),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 48378), 'yellow_cards', 2, 3, 4, 300, 6.63),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 733), 'yellow_cards', 3, 2, 5, 471, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 770), (SELECT id FROM players WHERE external_api_id = 30803), 'yellow_cards', 4, 2, 3, 40, 5.43),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 184), 'yellow_cards', 5, 2, 7, 606, 7.04),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 129718), 'yellow_cards', 6, 2, 7, 671, 7.44),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 47301), 'yellow_cards', 7, 2, 6, 443, 6.88),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 169), 'yellow_cards', 8, 2, 6, 453, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 162016), 'yellow_cards', 9, 2, 6, 456, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 290), 'yellow_cards', 10, 2, 6, 540, 7.10),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 67971), 'yellow_cards', 11, 2, 6, 570, 7.05),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 24903), 'yellow_cards', 12, 2, 5, 320, 6.96),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 272), 'yellow_cards', 13, 2, 5, 374, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 226), 'yellow_cards', 14, 2, 5, 449, 7.02),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 1271), 'yellow_cards', 15, 2, 5, 471, 7.38),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 2285), 'yellow_cards', 16, 2, 5, 480, 7.36),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 1), (SELECT id FROM players WHERE external_api_id = 24882), 'yellow_cards', 17, 2, 4, 130, 6.78),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 777), (SELECT id FROM players WHERE external_api_id = 37155), 'yellow_cards', 18, 2, 4, 229, 6.65),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 21), (SELECT id FROM players WHERE external_api_id = 1930), 'yellow_cards', 19, 2, 4, 282, 6.73),
((SELECT id FROM tournaments WHERE external_api_id = 4 AND season = '2024'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 22236), 'yellow_cards', 20, 2, 4, 289, 6.78)
ON CONFLICT (tournament_id, category, player_id)
DO UPDATE SET
    team_id = EXCLUDED.team_id,
    rank = EXCLUDED.rank,
    value = EXCLUDED.value,
    appearances = EXCLUDED.appearances,
    minutes_played = EXCLUDED.minutes_played,
    rating = EXCLUDED.rating;

COMMIT TRANSACTION;
