"""add_team_squads_job_name_to_enum

Revision ID: 03091417374b
Revises: 326269db92f3
Create Date: 2026-06-18 19:24:44.535073

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03091417374b"
down_revision: Union[str, Sequence[str], None] = "326269db92f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE job_name_enum ADD VALUE IF NOT EXISTS 'team_squads_refresh'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
