"""make_player_id_not_foreign_key_in_match_events

Revision ID: 11de22611646
Revises: 21017bca6214
Create Date: 2026-06-02 17:55:05.087643

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11de22611646"
down_revision: Union[str, Sequence[str], None] = "21017bca6214"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("match_events_player_external_id_fkey"), "match_events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("match_events_secondary_player_external_id_fkey"), "match_events", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("match_events_secondary_player_external_id_fkey"),
        "match_events",
        "players",
        ["secondary_player_external_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("match_events_player_external_id_fkey"),
        "match_events",
        "players",
        ["player_external_id"],
        ["id"],
    )
    # ### end Alembic commands ###
