"""add_player_leaderboards_table

Revision ID: 17a038169c0d
Revises: 4886ad313921
Create Date: 2026-06-21 19:36:58.594227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17a038169c0d"
down_revision: Union[str, Sequence[str], None] = "4886ad313921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    leaderboard_type_enum = postgresql.ENUM(
        "goals",
        "assists",
        "yellow_cards",
        name="leaderboard_type_enum",
        create_type=False,
    )

    leaderboard_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "player_leaderboards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("category", leaderboard_type_enum, nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("appearances", sa.Integer(), nullable=True),
        sa.Column("minutes_played", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tournament_id",
            "category",
            "player_id",
            name="uq_player_leaderboards_tournament_category_player",
        ),
    )
    op.create_index(
        "ix_player_leaderboards_player_id", "player_leaderboards", ["player_id"], unique=False
    )
    op.create_index(
        "ix_player_leaderboards_team_id", "player_leaderboards", ["team_id"], unique=False
    )
    op.create_index(
        "ix_player_leaderboards_tournament_category",
        "player_leaderboards",
        ["tournament_id", "category"],
        unique=False,
    )
    op.create_index(
        "ix_player_leaderboards_tournament_category_rank",
        "player_leaderboards",
        ["tournament_id", "category", "rank"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_player_leaderboards_tournament_category_rank", table_name="player_leaderboards"
    )
    op.drop_index("ix_player_leaderboards_tournament_category", table_name="player_leaderboards")
    op.drop_index("ix_player_leaderboards_team_id", table_name="player_leaderboards")
    op.drop_index("ix_player_leaderboards_player_id", table_name="player_leaderboards")
    op.drop_table("player_leaderboards")

    leaderboard_type_enum = postgresql.ENUM(
        "goals",
        "assists",
        "yellow_cards",
        name="leaderboard_type_enum",
        create_type=False,
    )

    leaderboard_type_enum.drop(op.get_bind(), checkfirst=True)


# ### end Alembic commands ###
