"""add match city and time elapsed

Revision ID: 2723cf04bfe5
Revises: 5ffa5e05f300
Create Date: 2026-05-29 20:58:16.245424

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2723cf04bfe5"
down_revision: Union[str, Sequence[str], None] = "5ffa5e05f300"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("matches", sa.Column("elapsed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "elapsed")
    op.drop_column("matches", "city")
    # ### end Alembic commands ###
