"""alter_player_model_with_nullables_and_new_display_name

Revision ID: 326269db92f3
Revises: 43bcc460f669
Create Date: 2026-06-17 15:35:20.039275

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "326269db92f3"
down_revision: Union[str, Sequence[str], None] = "43bcc460f669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("display_name", sa.String(length=150), nullable=False))
    op.alter_column("players", "first_name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column("players", "last_name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column("players", "date_of_birth", existing_type=sa.DATE(), nullable=True)
    op.alter_column("players", "nationality", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.create_index("ix_players_display_name", "players", ["display_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_players_display_name", table_name="players")
    op.alter_column("players", "nationality", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("players", "date_of_birth", existing_type=sa.DATE(), nullable=False)
    op.alter_column("players", "last_name", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("players", "first_name", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.drop_column("players", "display_name")
    # ### end Alembic commands ###
