"""add_team_rankings_refresh_job_name_to_enum_and_index_on_status

Revision ID: 43bcc460f669
Revises: 4581142c4dc1
Create Date: 2026-06-10 20:11:41.201958

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43bcc460f669"
down_revision: Union[str, Sequence[str], None] = "4581142c4dc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE job_name_enum ADD VALUE IF NOT EXISTS 'team_rankings_refresh'")
    op.create_index("ix_refresh_jobs_status", "refresh_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refresh_jobs_status", table_name="refresh_jobs")
    # ### end Alembic commands ###
