"""add_ranking_columns_to_tournament_teams

Revision ID: 4581142c4dc1
Revises: 591b26dcd8f0
Create Date: 2026-06-10 16:29:34.395242

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4581142c4dc1"
down_revision: Union[str, Sequence[str], None] = "591b26dcd8f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tournament_teams", sa.Column("final_rank", sa.Integer(), nullable=True))
    op.add_column(
        "tournament_teams",
        sa.Column(
            "stage_reached",
            sa.Enum(
                "group",
                "round_of_32",
                "round_of_16",
                "quarter_final",
                "semi_final",
                "third_place",
                "final",
                "other",
                name="stage_type_enum",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_tournament_teams_tournament_final_rank",
        "tournament_teams",
        ["tournament_id", "final_rank"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tournament_teams_tournament_final_rank", table_name="tournament_teams")
    op.drop_column("tournament_teams", "stage_reached")
    op.drop_column("tournament_teams", "final_rank")
    # ### end Alembic commands ###
