"""delete_player_stats_table

Revision ID: 4886ad313921
Revises: 024aff0fffbe
Create Date: 2026-06-21 18:03:34.966723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4886ad313921"
down_revision: Union[str, Sequence[str], None] = "024aff0fffbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_stats_player_id"), table_name="player_stats")
    op.drop_index(op.f("ix_player_stats_team_id"), table_name="player_stats")
    op.drop_index(op.f("ix_player_stats_tournament_id"), table_name="player_stats")
    op.drop_index(op.f("uq_player_stats_player_tournament_team"), table_name="player_stats")
    op.drop_table("player_stats")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tournament_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("appearances", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("minutes_played", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("goals", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("assists", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("yellow_cards", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("red_cards", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("player_stats_player_id_fkey")
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("player_stats_team_id_fkey")),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournaments.id"], name=op.f("player_stats_tournament_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("player_stats_pkey")),
    )
    op.create_index(
        op.f("uq_player_stats_player_tournament_team"),
        "player_stats",
        ["player_id", "tournament_id", "team_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_player_stats_tournament_id"), "player_stats", ["tournament_id"], unique=False
    )
    op.create_index(op.f("ix_player_stats_team_id"), "player_stats", ["team_id"], unique=False)
    op.create_index(op.f("ix_player_stats_player_id"), "player_stats", ["player_id"], unique=False)
    # ### end Alembic commands ###
