"""initial schema

Revision ID: 9041d854c954
Revises:
Create Date: 2026-05-05 22:36:28.118484

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9041d854c954"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Trigger helpers
#
# set_updated_at() is defined once and reused by every table with updated_at.
# Ensures the column is maintained correctly even outside of SQLAlchemy ORM
# calls (raw SQL, admin tools, sync jobs, etc.).
# ---------------------------------------------------------------------------

CREATE_UPDATED_AT_FUNCTION = """
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

DROP_UPDATED_AT_FUNCTION = "DROP FUNCTION IF EXISTS set_updated_at CASCADE;"


def _create_trigger(table: str) -> str:
    return f"""
    CREATE TRIGGER trg_{table}_updated_at
    BEFORE UPDATE ON {table}
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """


def _drop_trigger(table: str) -> str:
    return f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};"


TABLES_WITH_UPDATED_AT = [
    "players",
    "teams",
    "tournaments",
    "matches",
    "player_stats",
    "standings",
    "match_events",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cache_entries_cache_key"), "cache_entries", ["cache_key"], unique=True)
    op.create_index(
        op.f("ix_cache_entries_expires_at"), "cache_entries", ["expires_at"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_api_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("photo_url", sa.String(length=255), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=False),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_external_api_id"), "players", ["external_api_id"], unique=True)
    op.create_index(
        "ix_players_last_name_first_name", "players", ["last_name", "first_name"], unique=False
    )
    op.create_table(
        "refresh_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "success", "failed", name="job_status_enum"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_jobs_job_name"), "refresh_jobs", ["job_name"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_api_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=False),
        sa.Column("type", sa.Enum("national", "club", name="team_type_enum"), nullable=False),
        sa.Column("logo_url", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_external_api_id"), "teams", ["external_api_id"], unique=True)
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_index("ix_teams_name_country", "teams", ["name", "country"], unique=False)
    op.create_table(
        "tournaments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_api_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("season", sa.String(length=20), nullable=False),
        sa.Column("logo_url", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tournaments_external_api_id"), "tournaments", ["external_api_id"], unique=True
    )
    op.create_index(op.f("ix_tournaments_name"), "tournaments", ["name"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_api_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("team_a_id", sa.Integer(), nullable=False),
        sa.Column("team_b_id", sa.Integer(), nullable=False),
        sa.Column("kickoff_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "stage", sa.Enum("group", "knockout", "other", name="stage_type_enum"), nullable=False
        ),
        sa.Column("group", sa.String(length=10), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled", "live", "finished", "postponed", "cancelled", name="status_type_enum"
            ),
            nullable=False,
        ),
        sa.Column("venue", sa.String(length=100), nullable=True),
        sa.Column("team_a_score", sa.Integer(), nullable=True),
        sa.Column("team_b_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_external_api_id"), "matches", ["external_api_id"], unique=True)
    op.create_index("ix_matches_kickoff_time", "matches", ["kickoff_time"], unique=False)
    op.create_index("ix_matches_status", "matches", ["status"], unique=False)
    op.create_index("ix_matches_team_a_id", "matches", ["team_a_id"], unique=False)
    op.create_index("ix_matches_team_b_id", "matches", ["team_b_id"], unique=False)
    op.create_index("ix_matches_tournament_id", "matches", ["tournament_id"], unique=False)
    op.create_table(
        "player_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("appearances", sa.Integer(), nullable=False),
        sa.Column("minutes_played", sa.Integer(), nullable=False),
        sa.Column("goals", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("yellow_cards", sa.Integer(), nullable=False),
        sa.Column("red_cards", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_player_stats_player_id", "player_stats", ["player_id"], unique=False)
    op.create_index("ix_player_stats_team_id", "player_stats", ["team_id"], unique=False)
    op.create_index(
        "ix_player_stats_tournament_id", "player_stats", ["tournament_id"], unique=False
    )
    op.create_index(
        "uq_player_stats_player_tournament_team",
        "player_stats",
        ["player_id", "tournament_id", "team_id"],
        unique=True,
    )
    op.create_table(
        "standings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("group", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("goals_for", sa.Integer(), nullable=False),
        sa.Column("goals_against", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_standings_team_id", "standings", ["team_id"], unique=False)
    op.create_index(
        "ix_standings_tournament_group", "standings", ["tournament_id", "group"], unique=False
    )
    op.create_index("ix_standings_tournament_id", "standings", ["tournament_id"], unique=False)
    op.create_index(
        "uq_standings_tournament_team", "standings", ["tournament_id", "team_id"], unique=True
    )
    op.create_table(
        "team_players",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("squad_number", sa.Integer(), nullable=True),
        sa.Column(
            "position", sa.Enum("GK", "DEF", "MID", "FWD", name="position_type_enum"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("tournament_id", "team_id", "player_id"),
    )
    op.create_table(
        "tournament_teams",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("group", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("tournament_id", "team_id"),
    )
    op.create_table(
        "match_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("secondary_player_id", sa.Integer(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "goal",
                "own_goal",
                "penalty_goal",
                "penalty_miss",
                "assist",
                "yellow_card",
                "red_card",
                "substitution",
                name="event_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secondary_player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_match_events_match_id", "match_events", ["match_id"], unique=False)
    op.create_index("ix_match_events_player_id", "match_events", ["player_id"], unique=False)
    op.create_index("ix_match_events_team_id", "match_events", ["team_id"], unique=False)
    # ### end Alembic commands ###

    # ---------------------------------------------------------------------------
    # Triggers — applied after all tables are created
    # ---------------------------------------------------------------------------
    op.execute(CREATE_UPDATED_AT_FUNCTION)
    for table in TABLES_WITH_UPDATED_AT:
        op.execute(_create_trigger(table))


def downgrade() -> None:
    """Downgrade schema."""
    # Drop triggers before tables
    for table in reversed(TABLES_WITH_UPDATED_AT):
        op.execute(_drop_trigger(table))
    op.execute(DROP_UPDATED_AT_FUNCTION)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_events_team_id", table_name="match_events")
    op.drop_index("ix_match_events_player_id", table_name="match_events")
    op.drop_index("ix_match_events_match_id", table_name="match_events")
    op.drop_table("match_events")
    op.drop_table("tournament_teams")
    op.drop_table("team_players")
    op.drop_index("uq_standings_tournament_team", table_name="standings")
    op.drop_index("ix_standings_tournament_id", table_name="standings")
    op.drop_index("ix_standings_tournament_group", table_name="standings")
    op.drop_index("ix_standings_team_id", table_name="standings")
    op.drop_table("standings")
    op.drop_index("uq_player_stats_player_tournament_team", table_name="player_stats")
    op.drop_index("ix_player_stats_tournament_id", table_name="player_stats")
    op.drop_index("ix_player_stats_team_id", table_name="player_stats")
    op.drop_index("ix_player_stats_player_id", table_name="player_stats")
    op.drop_table("player_stats")
    op.drop_index("ix_matches_tournament_id", table_name="matches")
    op.drop_index("ix_matches_team_b_id", table_name="matches")
    op.drop_index("ix_matches_team_a_id", table_name="matches")
    op.drop_index("ix_matches_status", table_name="matches")
    op.drop_index("ix_matches_kickoff_time", table_name="matches")
    op.drop_index(op.f("ix_matches_external_api_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_tournaments_name"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_external_api_id"), table_name="tournaments")
    op.drop_table("tournaments")
    op.drop_index("ix_teams_name_country", table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_index(op.f("ix_teams_external_api_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_refresh_jobs_job_name"), table_name="refresh_jobs")
    op.drop_table("refresh_jobs")
    op.drop_index("ix_players_last_name_first_name", table_name="players")
    op.drop_index(op.f("ix_players_external_api_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_cache_entries_expires_at"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_cache_key"), table_name="cache_entries")
    op.drop_table("cache_entries")
    # ### end Alembic commands ###

    # Drop enum types: Postgres persists these independently of tables
    enum_names = [
        "event_type_enum",
        "position_type_enum",
        # "stage_type_enum", <- removed, owned by next migration
        "status_type_enum",
        "job_status_enum",
        "team_type_enum",
    ]

    for name in enum_names:
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
