"""add_player_leaderboards_job_name_to_enum

Revision ID: 960fc64c848a
Revises: 17a038169c0d
Create Date: 2026-06-22 18:59:25.278031

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "960fc64c848a"
down_revision: Union[str, Sequence[str], None] = "17a038169c0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE job_name_enum ADD VALUE IF NOT EXISTS 'team_squads_refresh'")
    op.execute("ALTER TYPE job_name_enum ADD VALUE IF NOT EXISTS 'player_leaderboards_refresh'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
