"""update matches stage to string

Revision ID: 97f606db7a1c
Revises: 9041d854c954
Create Date: 2026-05-09 19:31:13.852549

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97f606db7a1c"
down_revision: Union[str, Sequence[str], None] = "9041d854c954"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "stage",
        existing_type=postgresql.ENUM("group", "knockout", "other", name="stage_type_enum"),
        type_=sa.String(length=20),
        existing_nullable=False,
        postgresql_using="stage::text",
    )
    sa.Enum(name="stage_type_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    old_stage_type_enum = sa.Enum(
        "group",
        "knockout",
        "other",
        name="stage_type_enum",
    )

    old_stage_type_enum.create(op.get_bind(), checkfirst=True)

    op.execute("""
    UPDATE matches
    SET stage = 'knockout'
    WHERE stage IN (
        'round_of_32',
        'round_of_16',
        'quarter_final',
        'semi_final',
        'third_place',
        'final'
    )
    """)

    op.alter_column(
        "matches",
        "stage",
        existing_type=sa.String(length=20),
        type_=old_stage_type_enum,
        existing_nullable=False,
        postgresql_using="stage::stage_type_enum",
    )
    # ### end Alembic commands ###
