"""augment_match_event_model_with_new_attributes

Revision ID: 9eeea820c1df
Revises: d1b7ae21a6fd
Create Date: 2026-06-02 15:37:59.795719

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eeea820c1df"
down_revision: Union[str, Sequence[str], None] = "d1b7ae21a6fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_events", sa.Column("player_name", sa.String(length=100), nullable=True))
    op.add_column(
        "match_events", sa.Column("secondary_player_name", sa.String(length=100), nullable=True)
    )
    op.add_column("match_events", sa.Column("extra_minute", sa.Integer(), nullable=True))
    op.add_column("match_events", sa.Column("detail", sa.String(length=100), nullable=True))
    op.add_column("match_events", sa.Column("comments", sa.String(length=255), nullable=True))
    op.alter_column("match_events", "player_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("match_events", "player_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("match_events", "comments")
    op.drop_column("match_events", "detail")
    op.drop_column("match_events", "extra_minute")
    op.drop_column("match_events", "secondary_player_name")
    op.drop_column("match_events", "player_name")
    # ### end Alembic commands ###
