"""define stage type as an enum

Revision ID: b6dacc6713d8
Revises: 2723cf04bfe5
Create Date: 2026-05-29 21:11:45.048185

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6dacc6713d8"
down_revision: Union[str, Sequence[str], None] = "2723cf04bfe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "stage",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "group",
            "round_of_32",
            "round_of_16",
            "quarter_final",
            "semi_final",
            "third_place",
            "final",
            "other",
            name="stage_type_enum",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "stage",
        existing_type=sa.Enum(
            "group",
            "round_of_32",
            "round_of_16",
            "quarter_final",
            "semi_final",
            "third_place",
            "final",
            "other",
            name="stage_type_enum",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
