"""add penalty scores to matches

Revision ID: d1b7ae21a6fd
Revises: b6dacc6713d8
Create Date: 2026-05-31 21:15:06.301308

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1b7ae21a6fd"
down_revision: Union[str, Sequence[str], None] = "b6dacc6713d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("team_a_penalties", sa.Integer(), nullable=True))
    op.add_column("matches", sa.Column("team_b_penalties", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "team_b_penalties")
    op.drop_column("matches", "team_a_penalties")
    # ### end Alembic commands ###
