"""add_player_external_ids_to_match_events

Revision ID: eeef23beb34c
Revises: 9eeea820c1df
Create Date: 2026-06-02 16:05:55.663388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeef23beb34c"
down_revision: Union[str, Sequence[str], None] = "9eeea820c1df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_events", sa.Column("player_external_id", sa.Integer(), nullable=True))
    op.add_column(
        "match_events", sa.Column("secondary_player_external_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "match_events", "players", ["player_external_id"], ["id"])
    op.create_foreign_key(None, "match_events", "players", ["secondary_player_external_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match_events", type_="foreignkey")
    op.drop_constraint(None, "match_events", type_="foreignkey")
    op.drop_column("match_events", "secondary_player_external_id")
    op.drop_column("match_events", "player_external_id")
    # ### end Alembic commands ###
