BEGIN TRANSACTION;

INSERT INTO player_leaderboards (
    tournament_id,
    team_id,
    player_id,
    category,
    rank,
    value,
    appearances,
    minutes_played,
    rating
)
VALUES
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 744), 'goals', 1, 5, 7, 591, 6.94),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 36579), 'goals', 2, 5, 3, 591, 6.94),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 2780), 'goals', 3, 4, 6, 539, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 306), 'goals', 4, 4, 6, 569, 7.52),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 18767), 'goals', 5, 3, 6, 516, 7.82),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 2722), 'goals', 6, 3, 7, 477, 6.56),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1501), (SELECT id FROM players WHERE external_api_id = 157997), 'goals', 7, 3, 5, 353, 7.74),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 20696), 'goals', 8, 3, 6, 508, 7.52),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1532), (SELECT id FROM players WHERE external_api_id = 635), 'goals', 9, 3, 4, 269, 7.68),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1500), (SELECT id FROM players WHERE external_api_id = 90617), 'goals', 10, 3, 5, 451, 7.12),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 304), 'goals', 11, 2, 7, 646, 7.31),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 57446), 'goals', 12, 2, 7, 506, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1531), (SELECT id FROM players WHERE external_api_id = 98936), 'goals', 13, 2, 4, 343, 7.13),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1532), (SELECT id FROM players WHERE external_api_id = 380587), 'goals', 14, 2, 5, 325, 7.46),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 283058), 'goals', 15, 2, 5, 386, 6.78),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 81573), 'goals', 16, 2, 6, 463, 7.02),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 162219), 'goals', 17, 2, 5, 294, 7.30),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 28), (SELECT id FROM players WHERE external_api_id = 42012), 'goals', 18, 2, 4, 284, 6.95),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1530), (SELECT id FROM players WHERE external_api_id = 505295), 'goals', 19, 2, 4, 329, 6.75),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1501), (SELECT id FROM players WHERE external_api_id = 387643), 'goals', 20, 2, 3, 38, 7.60),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 18767), 'assists', 1, 4, 6, 516, 7.82),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 304), 'assists', 2, 3, 7, 646, 7.31),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 2780), 'assists', 3, 2, 6, 539, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 57446), 'assists', 4, 2, 7, 506, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1531), (SELECT id FROM players WHERE external_api_id = 98936), 'assists', 5, 2, 4, 343, 7.13),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 17269), 'assists', 6, 2, 6, 391, 6.97),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 1455), 'assists', 7, 2, 6, 505, 7.33),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 1696), 'assists', 8, 2, 5, 242, 7.73),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1532), (SELECT id FROM players WHERE external_api_id = 326067), 'assists', 9, 2, 4, 182, 6.85),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1502), (SELECT id FROM players WHERE external_api_id = 284797), 'assists', 10, 2, 4, 301, 6.58),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 28), (SELECT id FROM players WHERE external_api_id = 180560), 'assists', 11, 2, 4, 351, 7.28),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1489), (SELECT id FROM players WHERE external_api_id = 303493), 'assists', 12, 2, 4, 360, 7.05),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 129678), 'assists', 13, 2, 3, 225, 7.53),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1501), (SELECT id FROM players WHERE external_api_id = 20836), 'assists', 14, 2, 1, 90, 7.70),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 306), 'assists', 15, 1, 6, 569, 7.52),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 2722), 'assists', 16, 1, 7, 477, 6.56),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1501), (SELECT id FROM players WHERE external_api_id = 157997), 'assists', 17, 1, 5, 353, 7.74),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1532), (SELECT id FROM players WHERE external_api_id = 380587), 'assists', 18, 1, 5, 325, 7.46),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 283058), 'assists', 19, 1, 5, 386, 6.78),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1512), (SELECT id FROM players WHERE external_api_id = 154839), 'assists', 20, 1, 4, 330, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 152967), 'yellow_cards', 1, 3, 6, 525, 7.37),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1532), (SELECT id FROM players WHERE external_api_id = 326067), 'yellow_cards', 2, 3, 4, 182, 6.85),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1500), (SELECT id FROM players WHERE external_api_id = 18968), 'yellow_cards', 3, 2, 4, 288, 6.43),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1510), (SELECT id FROM players WHERE external_api_id = 575069), 'yellow_cards', 4, 2, 3, 150, 6.20),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 318), 'yellow_cards', 5, 2, 5, 364, 7.10),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 374058), 'yellow_cards', 6, 2, 7, 242, 6.71),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 2781), 'yellow_cards', 7, 2, 7, 302, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 20696), 'yellow_cards', 8, 2, 6, 508, 7.52),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 180728), 'yellow_cards', 9, 2, 6, 570, 7.38),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1500), (SELECT id FROM players WHERE external_api_id = 384473), 'yellow_cards', 10, 2, 5, 195, 6.54),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1500), (SELECT id FROM players WHERE external_api_id = 302869), 'yellow_cards', 11, 2, 5, 254, 6.78),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1530), (SELECT id FROM players WHERE external_api_id = 356041), 'yellow_cards', 12, 2, 5, 346, 6.84),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1530), (SELECT id FROM players WHERE external_api_id = 51107), 'yellow_cards', 13, 2, 5, 402, 6.68),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 32), (SELECT id FROM players WHERE external_api_id = 190575), 'yellow_cards', 14, 2, 5, 456, 7.10),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1489), (SELECT id FROM players WHERE external_api_id = 175417), 'yellow_cards', 15, 2, 4, 217, 6.70),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 327631), 'yellow_cards', 16, 2, 4, 225, 6.55),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1501), (SELECT id FROM players WHERE external_api_id = 474591), 'yellow_cards', 17, 2, 4, 280, 7.15),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1530), (SELECT id FROM players WHERE external_api_id = 294552), 'yellow_cards', 18, 2, 4, 284, 6.70),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 1531), (SELECT id FROM players WHERE external_api_id = 46334), 'yellow_cards', 19, 2, 4, 297, 6.90),
((SELECT id FROM tournaments WHERE external_api_id = 6 AND season = '2025'), (SELECT id FROM teams WHERE external_api_id = 19), (SELECT id FROM players WHERE external_api_id = 18786), 'yellow_cards', 20, 2, 4, 332, 7.30)
ON CONFLICT (tournament_id, category, player_id)
DO UPDATE SET
    team_id = EXCLUDED.team_id,
    rank = EXCLUDED.rank,
    value = EXCLUDED.value,
    appearances = EXCLUDED.appearances,
    minutes_played = EXCLUDED.minutes_played,
    rating = EXCLUDED.rating;

COMMIT TRANSACTION;
