BEGIN TRANSACTION;

INSERT INTO player_leaderboards (
    tournament_id,
    team_id,
    player_id,
    category,
    rank,
    value,
    appearances,
    minutes_played,
    rating
)
VALUES
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 278), 'goals', 1, 8, 7, 597, 7.61),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 154), 'goals', 2, 7, 7, 690, 8.31),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 6009), 'goals', 3, 4, 7, 467, 7.00),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 2295), 'goals', 4, 4, 6, 423, 7.23),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 41585), 'goals', 5, 3, 4, 164, 7.33),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 59), 'goals', 6, 3, 4, 183, 7.10),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 909), 'goals', 7, 3, 5, 148, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 247), 'goals', 8, 3, 5, 453, 7.48),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 1460), 'goals', 9, 3, 4, 293, 7.55),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 2413), 'goals', 10, 3, 4, 326, 7.43),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2382), (SELECT id FROM players WHERE external_api_id = 35533), 'goals', 11, 3, 3, 256, 7.33),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 25), (SELECT id FROM players WHERE external_api_id = 25391), 'goals', 12, 2, 3, 66, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1530), (SELECT id FROM players WHERE external_api_id = 386), 'goals', 13, 2, 3, 141, 7.40),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 3), (SELECT id FROM players WHERE external_api_id = 726), 'goals', 14, 2, 7, 481, 6.80),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 31), (SELECT id FROM players WHERE external_api_id = 47422), 'goals', 15, 2, 7, 547, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 22236), 'goals', 16, 2, 5, 88, 7.02),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 25416), 'goals', 17, 2, 4, 61, 6.97),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 12), (SELECT id FROM players WHERE external_api_id = 2598), 'goals', 18, 2, 4, 218, 7.18),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 17), (SELECT id FROM players WHERE external_api_id = 34211), 'goals', 19, 2, 4, 275, 6.98),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 15), (SELECT id FROM players WHERE external_api_id = 421), 'goals', 20, 2, 4, 326, 6.68),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 154), 'assists', 1, 3, 7, 690, 8.31),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 184), 'assists', 2, 3, 5, 404, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 1485), 'assists', 3, 3, 4, 357, 8.48),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 3), (SELECT id FROM players WHERE external_api_id = 207), 'assists', 4, 3, 7, 670, 7.20),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 56), 'assists', 5, 3, 7, 537, 7.70),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 278), 'assists', 6, 2, 7, 597, 7.61),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 3), (SELECT id FROM players WHERE external_api_id = 1330), 'assists', 7, 2, 6, 169, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 47300), 'assists', 8, 2, 6, 508, 7.32),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 226), 'assists', 9, 2, 5, 480, 6.88),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1118), (SELECT id FROM players WHERE external_api_id = 25321), 'assists', 10, 2, 4, 191, 7.08),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 10), (SELECT id FROM players WHERE external_api_id = 631), 'assists', 11, 2, 4, 259, 7.28),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 8), 'assists', 12, 2, 4, 279, 7.28),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 6), (SELECT id FROM players WHERE external_api_id = 762), 'assists', 13, 2, 4, 302, 7.00),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2384), (SELECT id FROM players WHERE external_api_id = 17), 'assists', 14, 2, 4, 315, 7.25),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 583), 'assists', 15, 2, 4, 333, 7.10),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 2), (SELECT id FROM players WHERE external_api_id = 153), 'assists', 16, 2, 7, 438, 6.86),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 9), (SELECT id FROM players WHERE external_api_id = 128), 'assists', 17, 2, 4, 266, 7.28),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 14), (SELECT id FROM players WHERE external_api_id = 579), 'assists', 18, 2, 3, 213, 7.27),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 14), (SELECT id FROM players WHERE external_api_id = 554), 'assists', 19, 2, 3, 258, 7.37),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 27), (SELECT id FROM players WHERE external_api_id = 41585), 'assists', 20, 1, 4, 164, 7.33),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 1493), 'yellow_cards', 1, 3, 6, 374, 6.93),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 2468), 'yellow_cards', 2, 3, 4, 118, 6.48),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 30776), 'yellow_cards', 3, 2, 7, 548, 6.76),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 3), (SELECT id FROM players WHERE external_api_id = 2291), 'yellow_cards', 4, 2, 7, 638, 7.13),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 624), 'yellow_cards', 5, 2, 7, 690, 6.97),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 26), (SELECT id FROM players WHERE external_api_id = 271), 'yellow_cards', 6, 2, 5, 224, 6.98),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 20), (SELECT id FROM players WHERE external_api_id = 2742), 'yellow_cards', 7, 2, 4, 190, 6.85),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 17), (SELECT id FROM players WHERE external_api_id = 2903), 'yellow_cards', 8, 2, 4, 304, 6.55),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 20), (SELECT id FROM players WHERE external_api_id = 2749), 'yellow_cards', 9, 2, 4, 355, 6.58),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 24), (SELECT id FROM players WHERE external_api_id = 19298), 'yellow_cards', 10, 2, 4, 360, 6.60),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 23), (SELECT id FROM players WHERE external_api_id = 44475), 'yellow_cards', 11, 2, 3, 196, 6.63),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 14), (SELECT id FROM players WHERE external_api_id = 45826), 'yellow_cards', 12, 2, 3, 236, 6.60),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 14), (SELECT id FROM players WHERE external_api_id = 2823), 'yellow_cards', 13, 2, 3, 246, 6.30),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 12), (SELECT id FROM players WHERE external_api_id = 38114), 'yellow_cards', 14, 2, 3, 270, 7.03),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 14), (SELECT id FROM players WHERE external_api_id = 2817), 'yellow_cards', 15, 2, 3, 270, 6.87),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1530), (SELECT id FROM players WHERE external_api_id = 2100), 'yellow_cards', 16, 2, 3, 270, 6.67),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 13), (SELECT id FROM players WHERE external_api_id = 2990), 'yellow_cards', 17, 2, 3, 270, 6.77),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 22), (SELECT id FROM players WHERE external_api_id = 2700), 'yellow_cards', 18, 2, 2, 58, 6.25),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 14), (SELECT id FROM players WHERE external_api_id = 1489), 'yellow_cards', 19, 2, 2, 92, 6.40),
((SELECT id FROM tournaments WHERE external_api_id = 1 AND season = '2022'), (SELECT id FROM teams WHERE external_api_id = 1), (SELECT id FROM players WHERE external_api_id = 162714), 'yellow_cards', 20, 2, 2, 105, 6.60)
ON CONFLICT (tournament_id, category, player_id)
DO UPDATE SET
    team_id = EXCLUDED.team_id,
    rank = EXCLUDED.rank,
    value = EXCLUDED.value,
    appearances = EXCLUDED.appearances,
    minutes_played = EXCLUDED.minutes_played,
    rating = EXCLUDED.rating;

COMMIT TRANSACTION;
