name: Refresh Tournament Data

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  refresh-tournament-data:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Refresh standings
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          API_FOOTBALL_API_KEY: ${{ secrets.API_FOOTBALL_API_KEY }}
        run: python database/scripts/refresh/refresh_standings.py

      - name: Refresh matches
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          API_FOOTBALL_API_KEY: ${{ secrets.API_FOOTBALL_API_KEY }}
        run: python database/scripts/refresh/refresh_matches.py